/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sahan.adyapana.gui;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

public class DashboardButton extends javax.swing.JPanel {

    JPanel mainPanel;
    JFrame jFrame;

    public DashboardButton(JPanel jPanel, JFrame jFrame) {
        initComponents();

        this.mainPanel = jPanel;
        this.jFrame = jFrame;

        if (Signin.getTypeId().equals("2")) {     //Teacher
            jButton13.setEnabled(false);
            jButton15.setEnabled(false);
            jButton20.setEnabled(false);
            jButton21.setEnabled(false);
        } else if (Signin.getTypeId().equals("3")) {     //Student
            jButton13.setEnabled(false);
            jButton15.setEnabled(false);
            jButton16.setEnabled(false);
            jButton14.setEnabled(false);
            jButton19.setEnabled(false);
            jButton20.setEnabled(false);
            jButton21.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(45, 45, 45, 45));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 20, 20));

        jButton13.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/teacher_reg.png"))); // NOI18N
        jButton13.setText("Teacher Registration");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);

        jButton15.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/subject_reg.png"))); // NOI18N
        jButton15.setText("Subject Registration");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);

        jButton16.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/class_reg.png"))); // NOI18N
        jButton16.setText("Class Registration");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton16);

        jButton14.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/student_reg.png"))); // NOI18N
        jButton14.setText("Student Registration");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);

        jButton17.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/payment_manage.png"))); // NOI18N
        jButton17.setText("Payment Management");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17);

        jButton19.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/attendance_manage.png"))); // NOI18N
        jButton19.setText("Student Attendance Management");
        jButton19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton19);

        jButton18.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/enrollment.png"))); // NOI18N
        jButton18.setText("Student & Teacher Enrollment");
        jButton18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18);

        jButton20.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/setup_database.png"))); // NOI18N
        jButton20.setText("Setup Database Connection");
        jButton20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton20);

        jButton21.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/backup_database.png"))); // NOI18N
        jButton21.setText("Backup Database");
        jButton21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton21);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        TeacherRegistration teacherRegistration = new TeacherRegistration();
        mainPanel.add(teacherRegistration, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed

        new SetupConnection(null, true, true, this.jFrame).setVisible(true);

    }//GEN-LAST:event_jButton20ActionPerformed


    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        SubjectRegistration subjectRegistration = new SubjectRegistration();
        mainPanel.add(subjectRegistration, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        StudentRegistration studentRegistration = new StudentRegistration();
        mainPanel.add(studentRegistration, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);

    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        ClassRegistration classRegistration = new ClassRegistration();
        mainPanel.add(classRegistration, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);


    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        StudentPaymentManagement studentPaymentManagement = new StudentPaymentManagement();
        mainPanel.add(studentPaymentManagement, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);


    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        TeacherStudentEnrollment teacherStudentEnrollment = new TeacherStudentEnrollment();
        mainPanel.add(teacherStudentEnrollment, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);


    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        StudentAttendanceManagement studentAttendanceManagement = new StudentAttendanceManagement();
        mainPanel.add(studentAttendanceManagement, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

        mainPanel.setLayout(new BorderLayout());
        mainPanel.removeAll();

        DatabaseBackup databaseBackup = new DatabaseBackup();
        mainPanel.add(databaseBackup, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(mainPanel);

    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
