/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sahan.adyapana.gui;

import com.sahan.adyapana.model.MySQL;
import com.sahan.adyapana.model.SendEmail;
import com.sun.mail.util.MailConnectException;
import java.awt.Color;
import java.awt.Toolkit;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Sahan Liyanage
 */
public class Signin extends javax.swing.JFrame {

    static String nic;
    static String email;
    static String fname;
    static String lname;
    static String gender_id;
    static String type_id;

    public static String getUsername() {
        return nic;
    }

    public static String getEmail() {
        return email;
    }

    public static String getFname() {
        return fname;
    }

    public static String getLname() {
        return lname;
    }

    public static String getGenderId() {
        return gender_id;
    }

    public static String getTypeId() {
        return type_id;
    }

    public Signin() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/com/sahan/adyapana/recources/logo.jpg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Signin Panel");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 500, 50));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, 100, 50));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 158, 90, -1));

        jTextField1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("Type your nic here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 98, 330, 40));

        jPasswordField1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setToolTipText("Type your password here");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 154, 280, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/hide.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 154, 50, 40));

        jButton2.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jButton2.setText("Sign In");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 244, 440, 50));

        jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Forgot Password?");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (jPasswordField1.getEchoChar() == '\u2022') {
            jPasswordField1.setEchoChar('\u0000');
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/show.png")));
        } else if (jPasswordField1.getEchoChar() == '\u0000') {
            jPasswordField1.setEchoChar('\u2022');
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sahan/adyapana/recources/hide.png")));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (new File("dbinfo.ser").exists()) {

            nic = jTextField1.getText();
            String password = String.valueOf(jPasswordField1.getPassword());

            if (nic.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please enter your username(NIC).",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                jTextField1.grabFocus();

            } else if (password.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please enter your password",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                jPasswordField1.grabFocus();

            } else if (!password.matches("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@$!%*#?&])"
                    + "[A-Za-z\\d@$!%*#?&]{8,}$") | password.length() < 8 | password.length() > 20) {

                JOptionPane.showMessageDialog(this, "Password must be contained "
                        + "minimum 8 characters and maximum 20 characters, at least one letter, one "
                        + "number and one special character.",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                jPasswordField1.grabFocus();

            } else {

                boolean canContinue = false;

                try {

                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `teachers` WHERE `nic`='" + nic + "' AND `status_id`='1'");

                    if (resultSet.next()) {

                        ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `teachers` WHERE `nic`='" + nic + "' "
                                + "AND `password`='" + password + "' AND `status_id`='1'");

                        if (resultSet2.next()) {

                            email = resultSet2.getString("email");
                            fname = resultSet2.getString("fname");
                            lname = resultSet2.getString("lname");
                            gender_id = resultSet2.getString("gender_id");
                            type_id = resultSet2.getString("type_id");
                            canContinue = true;

                        } else {
                            JOptionPane.showMessageDialog(this, "Incorrect Password!",
                                    "Warning", JOptionPane.WARNING_MESSAGE);

                            jPasswordField1.grabFocus();
                        }

                    } else {

                        ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `students` WHERE `nic`='" + nic + "' AND `status_id`='1'");

                        if (resultSet2.next()) {

                            ResultSet resultSet3 = MySQL.executeSearch("SELECT * FROM `students` WHERE `nic`='" + nic + "' "
                                    + "AND `password`='" + password + "' AND `status_id`='1'");

                            if (resultSet3.next()) {

                                email = resultSet3.getString("email");
                                fname = resultSet3.getString("fname");
                                lname = resultSet3.getString("lname");
                                gender_id = resultSet3.getString("gender_id");
                                type_id = "3";
                                canContinue = true;

                            } else {
                                JOptionPane.showMessageDialog(this, "Incorrect Password!",
                                        "Warning", JOptionPane.WARNING_MESSAGE);

                                jPasswordField1.grabFocus();
                            }

                        } else {

                            JOptionPane.showMessageDialog(this, "Incorrect Username!",
                                    "Warning", JOptionPane.WARNING_MESSAGE);

                            jTextField1.grabFocus();

                        }
                    }

                    if (canContinue) {
                        this.dispose();
                        new Dashboard().setVisible(true);
                    }

                } catch (Exception e) {
                    e.printStackTrace();

                    JOptionPane.showMessageDialog(this, "Database Communication Error. Please Setup Database Connection First.",
                            "Error", JOptionPane.ERROR_MESSAGE);

                    this.dispose();
                    new SetupConnection(null, true, false, null).setVisible(true);
                }

            }

        } else {

            JOptionPane.showMessageDialog(this, "Please Setup Database Connection First.",
                    "Error", JOptionPane.ERROR_MESSAGE);

            this.dispose();
            new SetupConnection(null, true, false, null).setVisible(true);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        if (new File("dbinfo.ser").exists()) {

            String nic = jTextField1.getText();

            if (nic.isEmpty()) {

                JOptionPane.showMessageDialog(this, "Please enter your username(NIC).",
                        "Warning", JOptionPane.WARNING_MESSAGE);

                jTextField1.grabFocus();

            } else {

                try {

                    boolean canSend = false;

                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `teachers` WHERE `nic`='" + nic + "' AND `status_id`='1'");

                    String recipient = "";
                    String gender = "";
                    String fname = "";
                    String password = "";

                    if (resultSet.next()) {
                        recipient = resultSet.getString("email");
                        gender = resultSet.getString("gender_id");
                        fname = resultSet.getString("fname");
                        password = resultSet.getString("password");
                        canSend = true;
                    } else {

                        ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `students` WHERE `nic`='" + nic + "' AND `status_id`='1'");

                        if (resultSet2.next()) {
                            recipient = resultSet2.getString("email");
                            gender = resultSet2.getString("gender_id");
                            fname = resultSet2.getString("fname");
                            password = resultSet2.getString("password");
                            canSend = true;
                        } else {

                            JOptionPane.showMessageDialog(this, "Entered NIC is not registered in our database.\nPlease check again!",
                                    "Error", JOptionPane.ERROR_MESSAGE);

                            jTextField1.grabFocus();

                        }
                    }

                    if (canSend) {

                        if (gender.equals("1")) {
                            gender = "Mr.";
                        } else if (gender.equals("2")) {
                            gender = "Miss.";
                        }

                        new SendEmail().sendEmail(recipient, "Adyapana Institute Password Reminder", "Hello " + gender + fname + ",\n Your Account Password is " + password);

                        JOptionPane.showMessageDialog(this, "Your Account Password has been sent to " + recipient,
                                "Success", JOptionPane.INFORMATION_MESSAGE);

                        jPasswordField1.grabFocus();
                    }

                } catch (MailConnectException e) {

                    JOptionPane.showMessageDialog(this, "No Internet Connection.",
                            "Error", JOptionPane.ERROR_MESSAGE);

                } catch (Exception e) {
                    e.printStackTrace();

                    JOptionPane.showMessageDialog(this, "Database Communication Error. Please Setup Database Connection First.",
                            "Error", JOptionPane.ERROR_MESSAGE);

                    this.dispose();
                    new SetupConnection(null, true, false, null).setVisible(true);
                }

            }

        } else {

            JOptionPane.showMessageDialog(this, "Please Setup Database Connection First.",
                    "Error", JOptionPane.ERROR_MESSAGE);

            this.dispose();
            new SetupConnection(null, true, false, null).setVisible(true);

        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        jPasswordField1.grabFocus();

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed

        jButton2.grabFocus();

    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed

        Color lightCyan = new Color(102, 255, 255);
        jLabel5.setForeground(lightCyan);

    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased

        Color cyan = new Color(204, 255, 255);
        jLabel5.setForeground(cyan);

    }//GEN-LAST:event_jLabel5MouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
